platform :ios, '13.0'

#source 'ssh://git@us003.fly-access.com:7999/msdk/ios-internal-cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

# Use framworks instead of static libraries, swift does not support it
use_frameworks!


target 'DSS' do
  pod 'DJI-SDK-iOS', '4.16.1'
  pod 'DJI-UXSDK-iOS', '4.16'
  pod 'DJIWidget', '1.6.7'
  pod 'DJIFlySafeDatabaseResource', '01.00.01.18'
  pod 'SwiftyZeroMQ5'
  pod 'SwiftyJSON'
  pod 'Surge'
end

deployment_target = '12.0'

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
